### ISSUE TITLE
Minor point release 0.1.9.1 broke builds with GHC 7.6.3

### ISSUE THREAD

**Issue by ozataman** [fpco/streaming-commons#16] opened 2015-01-14 16:27 UTC
Here's a command that used to run fine on a brand new ubuntu image on AWS after initial GHC 7.6.3 installation:

```
cabal install cabal-src happy alex
```

Yet it all of a sudden stopped working after the 0.1.9.1 point release (!!) and now requires:

```
cabal install cabal-src happy alex --constrain 'streaming-commons < 0.1.9'
```

The lack of lower and upperbounds on dependencies is the culprit, I believe. At the very least, I personally find this kind of breakage to be beyond acceptable norms on a minor version bump. Wanted to make you guys aware.

Our standard version restrictions that *should* catch this issue will therefore have no effect:

```streaming-commons  >= 0.1 && < 0.2```

**Comment by snoyberg** [comment] 2015-01-14 16:38
Please don't give bug reports with enough information to actually solve
anything. What actually broke? What's the message? By saying a point
release broke it, which version stool works?

**Comment by snoyberg** [comment] 2015-01-14 16:47
If my previous response sounded annoyed, it's because of the accusatory nature if the report. We tested this release on many versions of GHC, as can be seen

https://travis-ci.org/fpco/streaming-commons

So before making claims of unacceptable behavior, please actually provide some real information about what's happening.

**Comment by ozataman** [comment] 2015-01-14 17:11
No need to get aggressive, Michael. It won't magically solve the issues people may be having in the wild using your packages. As you're doing a great service by maintaining this package, we're trying to do a service by reporting issues. I could have simply added my constraint and moved on instead of reporting, which is what responses like this will have me do in the future. 

The report was not as accusatory as it was frustrated, as we all are when dealing with dependency hell and things breaking under our feet. We are in fact quite careful in dependency management with lower-upper bounds on most outside packages, so breakages like this are unexpected. In the end though, my report was a simple statement of my observations and opinions, as you'll see in the language qualifiers in the right places.

The detail you asked for is:

```haskell
Preprocessing library streaming-commons-0.1.9.1...

Data/Streaming/ByteString/Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
```

I believe the following factors to be incompatible; I certainly may be wrong as I don't know your testing setup in detail. I particularly am not up to speed with your recent LTS/Stackage work, so have no idea if that somehow plays into the stability you see in your Travis tests. 

- I'm guessing you changed the import (i.e. module name/interface) on an underlying dependency
- You don't have lower/upper bounds on dependencies - which is heavily contested on either side of the aisle, so no judgements here
- The version bump stayed within the 0.1.xxx chain

When combined, these factors mean that we can't rely on the stability promised within the 0.1.xxx chain of versions. 

The following is enough on our machine to reliably trigger the issue:

```
mkdir foo
cd foo
cabal sandbox init
cabal install streaming-commons
```

**Comment by snoyberg** [comment] 2015-01-14 18:41
Believe me when I tell you that I deal with a large number of bug reports on a regular basis. Your original report left out crucial details, jumped to conclusions, and had an accusatory tone. That may not have been your intention, but that's how it reads.

I have written many blog posts and emails about fragile setups. If this change led to serious frustration and breakage in your internal setup, I recommend considering a more robust setup. I have many recommendations and ideas on that if you would like some advice.

Regarding breakage itself: @manny-fp, can you have a look?

**Comment by manny-fp** [comment] 2015-01-14 18:52
@ozataman To help my testing, which version of cabal-install are you using?  If you have bytestring < 0.10.2.0, it *should* be pulling in the `bytestring-builder` package which has the Data.ByteString.Builder.Extra module (with bytestring >= 0.10.2.0, bytestring itself includes that module).  I believe that I tested with cabal-install-1.20.0.3.

**Comment by snoyberg** [comment] 2015-01-14 18:57
@manny-fp That's a good question. There were certainly cabal-install dependency solver bugs around flags in the past. It caused a ridiculously large amount of problems for transformers-compat, for instance.

**Comment by ozataman** [comment] 2015-01-16 06:01
@manny-fp The machine where we saw this issue has already been shut down, but our boot script pulls and installs cabal-install-1.20.0.3.tar.gz.

**Comment by ozataman** [comment] 2015-01-16 06:20
@snoyberg No frustration; it's a 5 second fix: 'streaming-commons < 0.1.9'.

I would nevertheless love to hear what you consider to be a robust setup for a company-internal Haskell build ecosystem. Several requirements go into it (private repos, ability to quickly benefit from fixes/improvements, mobility, ability to fix some packages internally until maintainer gets up to speed, different major apps depending on different versions/branches of same package, ...) - happy to chat further if you feel like discussing.

**Comment by snoyberg** [comment] 2015-01-16 06:24
I'm just prepping for a trip, so I don't have time to go into details. But short answer is: reproducibility. Every developer should be able to run the `build-all` command and be guaranteed they're getting *exactly* the same versions of packages. One developer/curator/maintainer should have the responsibility of testing out new versions of packages and pushing an update to the entire team. The Stackage approaches to this are either a cabal.config file with constraints or a dedicated remote-repo with a single version of each package. Other options are:

* Incredibly restrictive .cabal files, though that's very difficult to maintain correctly
* Custom-written build tool with this knowledge built in (very heavyweight)
* Pre-built binary package databases. We're moving over to this approach internally (and basing it on the Stackage package sets), and distributing with Docker.

So my vote goes for (1) choose a Stackage Nightly or LTS Haskell, (2) build it in a Docker image, and (3) have everyone build in Docker. The cabal.config approach gets you about 75% of the benefits of that, and is much easier to do with the existing tools, so I'd recommend that for now. We'll be releasing the Docker-based tooling when it's more mature.

I guess I didn't go with a short response after all ;)

**Comment by manny-fp** [comment] 2015-01-19 11:42
For anyone still experiencing this issue, can you provide the output of `cabal install -v3 streaming-commons-0.1.9.1`?  If using GHC 7.6.3, it *should* contain something like this, where it decides to install bytestring-builder since you have an older version of bytestring that doesn't include Data.ByteString.Builder:

```
[_24] rejecting: streaming-commons-0.1.9.1:-use-bytestring-builder (conflict: unix => bytestring==0.10.0.2/installed-4f9..., streaming-commons-0.1.9.1:use-bytestring-builder => bytestring>=0.10.2.0)
[_24] trying: streaming-commons-0.1.9.1:+use-bytestring-builder
[_25] trying: bytestring-builder-0.10.4.0.1/installed-358... (dependency of streaming-commons-0.1.9.1:+use-bytestring-builder)
```

**Comment by reite** [comment] 2015-01-19 12:02
Im experiencing this error. Im using windows 8, cabal-install  1.22.0.0, GHC 7.6.3.

When I just do:
`cabal sandbox init`
`cabal install streaming-commons`

I get the same error as in the above post:
```
Data\Streaming\ByteString\Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
```

When I do `cabal install -v3 streaming-commons-0.1.9.1`. I get these lines:

```
[_24] rejecting: streaming-commons-0.1.9.1:-use-bytestring-builder (conflict: blaze-builder => bytestring==0.10.0.2/installed-c8f..., streaming-commons-0.1.9.1:use-bytestring-builder => bytestring>=0.10.2.0)
[_24] trying: streaming-commons-0.1.9.1:+use-bytestring-builder
[_25] done
```

Further down it also says: `Flags chosen: use-bytestring-builder=True`

`bytestring-builder` is also listed in the dependencies:

```
Dependency bytestring ==0.10.0.2: using bytestring-0.10.0.2
Dependency bytestring-builder ==0.10.4.0.1: using
bytestring-builder-0.10.4.0.1
```

However It still fails to install with this error:

```
Data\Streaming\ByteString\Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    Perhaps you meant
      Data.ByteString.Lazy.Builder.Extras (from bytestring-0.10.0.2)
    Locations searched:
      dist/dist-sandbox-3d043d22\build\Data\ByteString\Builder\Extra.hs
      dist/dist-sandbox-3d043d22\build\Data\ByteString\Builder\Extra.lhs
      Data\ByteString\Builder\Extra.hs
      Data\ByteString\Builder\Extra.lhs
      dist/dist-sandbox-3d043d22\build\autogen\Data\ByteString\Builder\Extra.hs
      dist/dist-sandbox-3d043d22\build\autogen\Data\ByteString\Builder\Extra.lhs
```

Here is the complete output from running the command:
https://gist.github.com/reite/37feee0dceaea88dd77e

**Comment by lseppala** [comment] 2015-01-20 00:26
This seems to be a library resolution bug in the latest Cabal library (`1.22.0.0`) at least on GHC `7.6.3`. Here's a minimally failing Dockerfile (last line fails with the error previously reported): 

```dockerfile
FROM debian:testing

ENV LANG en_US.UTF-8

# locales stuff to fix encoding issues
RUN apt-get update && apt-get install -y locales zlib1g-dev \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales \
    && apt-get install -y ghc cabal-install && cabal update

RUN cabal install cabal
RUN cabal install streaming-commons
```

Take out the second to the last line (upgrading cabal) and it builds.

I honestly don't have too much of any idea to go about fixing or circumventing this issue for now. Oddly enough, explicitly setting `bytestring` to `>= 0.10.4` in my Cabal file fixed this issue... can't say if that'll always work, though.

**Comment by manny-fp** [comment] 2015-01-20 01:15
@lseppala Thank you, I am now able to reproduce this in Docker.

**Comment by manny-fp** [comment] 2015-01-20 17:23
This turns out to be caused by lpsmith/bytestring-builder#1.  This is not a problem if using GHC 7.8 (which includes a new enough version of bytestring that bytestring-builder is not necessary).  If using GHC < 7.8, the workaround is to ensure your version of the Cabal library is < 1.19.  Alternatively, you can install a recent version of bytestring (with all the risks inherent in using a version of bytestring newer than that included with GHC).

**Comment by snoyberg** [comment] 2015-01-21 01:32
I just sent a pull request for that bytestring-builder bug: lpsmith/bytestring-builder#2.

**Comment by mightybyte** [comment] 2015-01-21 22:58
@manny-fp As an outsider having taken only a cursory look at this issue, I don't see how the problem could have been caused by bytestring-builder.  The last bytestring-builder release before today was December 2, 2013!  Things seem to have been working for over a year so I fail to see how that could be the cause of this recent problem.

It seems more likely that the problem is related to streaming-commons adding bytestring-builder as a new dependency a week ago along with exporting a new module and without a major version bump.  Either that or possibly something related to possible bugs in recent Cabal/cabal-install releases.

**Comment by snoyberg** [comment] 2015-01-21 23:11
@mightybyte 

1. We didn't release a new module in a patch release, it was the 0.1.9 minor version bump (the original report here was incorrect).
2. Please review that bytestring-builder issue, it incorrectly builds with specific versions of the Cabal library in place. @manny-fp's assessment of the situation is correct, and I (or you) can easily reproduce the results.

**Comment by mightybyte** [comment] 2015-01-21 23:59
@snoyberg Think about it from the users' perspective.  They're using package foo, it works, life is great.  The maintainer makes a change to foo, now it doesn't work, therefore the maintainer is the cause of the breakage.  Maybe the maintainer started depending on another package that has a problem.  Fine, but he is still the cause of the breakage in foo because he made the change that triggered the breakage.

I'm not here to harp on you for making mistakes.  I make plenty of them myself.  But I would like to suggest that maybe this change should have been accompanied by a major (not minor) version bump for two reasons.  One: you're exporting a new module.  Yes, I know that the letter of the PVP says that only needs a minor bump, but it also points out that this is risky and there are cases where it needs a major bump.  Two: you're adding a dependency on a new package.  That's potentially a big thing in terms of overall build risk.  Especially in this case where it is performing a fragile compatibility balance between old and new versions.  The PVP doesn't specifically discuss what to do when new dependencies are added, but it does say "Note that modifying imports or depending on a newer version of another package may cause extra orphan instances to be exported and thus force a major version change."  This just says depending on a new version of a package.  Depending on a completely new package has to be higher risk than that.

Now it's easy for a Monday morning quarterback to say "you broke something, therefore you should have made a major bump."  That's not what I'm trying to do here.  My point is that ultimately it's not about which sentence of the PVP was violated or not violated.  I think we need to view the spirit of the PVP as about preventing problems.  There is no oracle for predetermining whether a change will cause problems for people, so I think we need to look at it as more of a risk spectrum.  The PVP points out some things that are clearly higher risk.  But maybe there are other things (like adding a new dependency) that are also higher than normal risk and might merit a major version bump.

**Comment by snoyberg** [comment] 2015-01-22 00:07
@mightybyte I'm surprised you're really discussing this. This is such an obvious issue: there's a compatibility package for old versions of GHC. We used that package. We tested that everything worked. We released a new version, following the PVP. Then it turns out that under certain circumstances, that package is broken. And then we sent a pull request (two, actually) to get the package fixed.

Besides being perfectly prescient and realizing that this bug would occur, I can see nothing better that could have occurred here. If you think that every time a new package dependency is added we need a major version bump, go request a change to the PVP.

**Comment by marco-santamaria** [comment] 2015-01-22 09:17
I'm using version 1.22.0.0 of the Cabal library with version 7.6.3 of GHG and I get this error:

    Data/Streaming/ByteString/Builder.hs:12:8:
        Could not find module `Data.ByteString.Builder.Extra'
        It is a member of the hidden package `bytestring-0.10.4.1'.
        Perhaps you need to add `bytestring' to the build-depends in your .cabal file.
        Use -v to see a list of the files searched for.

I tried to also Cabal 1.18.1.6 with no luck

**Comment by manny-fp** [comment] 2015-01-22 11:57
@marco-santamaria Would you mind providing the output of `cabal install -v3 streaming-commons` and `ghc-pkg list`?

**Comment by marco-santamaria** [comment] 2015-01-22 13:15
With -v3 the relevant part should be the following:

    Data/Streaming/ByteString/Builder.hs:12:8:
    Could not find module `Data.ByteString.Builder.Extra'
    It is a member of the hidden package `bytestring-0.10.4.1'.
    Perhaps you need to add `bytestring' to the build-depends in your .cabal file.
        Locations searched:
          dist/build/Data/ByteString/Builder/Extra.hs
          dist/build/Data/ByteString/Builder/Extra.lhs
          Data/ByteString/Builder/Extra.hs
          Data/ByteString/Builder/Extra.lhs
          dist/build/autogen/Data/ByteString/Builder/Extra.hs
          dist/build/autogen/Data/ByteString/Builder/Extra.lhs

For ghc-pkg list see https://gist.github.com/marco-santamaria/80ee35ab73c186fc7966.
Thanks!

**Comment by manny-fp** [comment] 2015-01-22 14:11
@marco-santamaria The parts of the `-v3` output I'm particularly interested in are related to cabal's dependency solver, anything related to the `use-bytestring-builder` flag, and the full command-line it passes to GHC to build the package.  Rather than you going through the output looking for those, might be easiest to provide the all the output.

**Comment by marco-santamaria** [comment] 2015-01-22 15:31
Thanks for the feedback, I ended up removing all the installed packages, cabal and ghc. After reinstalling ghc and cabal now I don't have errors anymore using version 1.22.0.0 of the Cabal library and version 7.6.3 of GHG.

**Comment by snoyberg** [comment] 2015-02-09 10:24
bytestring-builder has released a patched version, which seems to have fixed this breakage. @ozataman @mightybyte can you test/confirm?

**Comment by manny-fp** [comment] 2015-02-23 14:22
Is anyone still experiencing problems?  If I don't hear back in the next few days, I'll close this issue.

**Closed** 2015-03-02 13:57 UTC
